# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Yet Another Open Source Blog
email: epsi.nurwijayadi@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Learn and Discover Open Source with Daily Genuine Experience.
  From Coding, Design, Package Management Tweak to Desktop Customization.
baseurl: "" # the subpath of your site, e.g. /blog

# the base hostname & protocol for your site
url: "http://epsi-rns.github.io" 

#opengraph
locale: en_US
logo: /assets/site/images/authors/epsi-vexel.png


paginate: 7
paginate_path: "blog/page:num"

# Build settings
markdown: kramdown

future: false

gems:
   - jekyll-paginate
#  - jemoji

# Google Analytics key, leave blank to ignore
google_analytics_key: true
# Yandex metrika (https://metrica.yandex.com/) leave blank to ignore or put true to use
yandex_metrica: true

google_adsense: true

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: epsirnsgithubio
comments: true
